# Generated by Django 3.0.1 on 2019-12-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20191226_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(help_text='Enter factory name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='object',
            field=models.CharField(help_text='Enter product name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(help_text='Enter product description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Enter product description', null=True),
        ),
    ]
