# Generated by Django 3.0.1 on 2020-01-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20200105_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(help_text='Enter product color', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discountRange',
            field=models.CharField(help_text='Enter product discountRange', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(help_text='Enter category name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(help_text='Enter country name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='object',
            field=models.CharField(help_text='Enter object', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.TextField(help_text='Enter review', null=True),
        ),
    ]
