# Generated by Django 3.0.1 on 2020-01-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_auto_20200105_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountRange',
            field=models.IntegerField(help_text='Enter product discountRange', max_length=200, null=True),
        ),
    ]
