# Generated by Django 3.0.1 on 2019-12-25 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myshop', '0004_auto_20191226_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('customer', models.CharField(max_length=13)),
                ('seller', models.CharField(max_length=13)),
                ('sale_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.Product')),
            ],
        ),
    ]
