# Generated by Django 3.0.1 on 2020-01-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20200105_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='birthday',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
